function gen_exp_params(dir_path, exp_name, label, duration_s)
    sequence = struct(...
        'label', label, ...
        'duration_s', duration_s, ...
        'nb', length(label) ...
    );

    save(fullfile(dir_path, exp_name + ".mat"), 'sequence');
    fprintf("[Saved] : Sequence information experiment %s", exp_name);
end